# Generated by Django 5.1.7 on 2025-03-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha específica')),
                ('day', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=15, verbose_name='Día')),
                ('total_calories', models.PositiveIntegerField(default=0, verbose_name='Calorías totales')),
            ],
        ),
        migrations.CreateModel(
            name='SemanalDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Inicio de semana')),
                ('finish_date', models.DateField(verbose_name='Fin de semana')),
                ('goal', models.CharField(blank=True, max_length=100, verbose_name='Objetivo de la semana')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('merienda', 'Merienda'), ('cena', 'Cena')], max_length=10, verbose_name='Tipo de comida')),
                ('food', models.JSONField(verbose_name='Alimentos consumidos')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total_calories_per_food', models.PositiveIntegerField(default=0, verbose_name='Calorías totales')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='diets.daydiet')),
            ],
        ),
        migrations.AddField(
            model_name='daydiet',
            name='semanal_diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='diets.semanaldiet'),
        ),
    ]
