# Generated by Django 5.2 on 2025-04-28 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('calories_per_100g', models.PositiveIntegerField(verbose_name='Calorías (por 100g)')),
                ('category', models.CharField(choices=[('fruta', 'Fruta'), ('verdura', 'Verdura'), ('lácteo', 'Lácteo'), ('cereal', 'Cereal'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='food',
        ),
        migrations.AddField(
            model_name='semanaldiet',
            name='precargado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semanaldiet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_semanaldiets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='diets.fooditem', verbose_name='Alimento'),
        ),
    ]
