# Generated by Django 5.2 on 2025-04-28 08:53

from django.db import migrations


def poblar_alimentos(apps, schema_editor):
    FoodItem = apps.get_model('diets', 'FoodItem')

    pera = FoodItem.objects.create(name="Pera", calories_per_100g=100, category="fruta")

class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0002_fooditem_remove_food_food_semanaldiet_precargado_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_alimentos),
    ]
