# Generated by Django 5.2 on 2025-04-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0003_auto_20250428_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semanaldiet',
            name='goal',
        ),
        migrations.AddField(
            model_name='semanaldiet',
            name='name',
            field=models.CharField(default='Semana 1', max_length=100, verbose_name='Nombre, ej: Semana 1'),
        ),
    ]
