# Generated by Django 5.2 on 2025-04-28 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0004_remove_semanaldiet_goal_semanaldiet_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semanaldiet',
            unique_together={('user', 'name')},
        ),
    ]
