# Generated by Django 5.2 on 2025-04-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0007_fooditem_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daydiet',
            options={'ordering': ['moment']},
        ),
        migrations.AlterUniqueTogether(
            name='daydiet',
            unique_together={('semanal_diet', 'moment', 'food_item')},
        ),
        migrations.RemoveField(
            model_name='daydiet',
            name='date',
        ),
    ]
