# Generated by Django 5.2 on 2025-04-30 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0009_day_alter_daydiet_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['day']},
        ),
        migrations.AddField(
            model_name='day',
            name='semanal_diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='days', to='diets.semanaldiet'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('semanal_diet', 'day')},
        ),
    ]
