# Generated by Django 5.2 on 2025-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0010_alter_day_options_day_semanal_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='diary_calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Calorías objetivo del día'),
        ),
    ]
