# Generated by Django 5.1.7 on 2025-05-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0011_day_diary_calories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='daydiet',
            unique_together={('day', 'moment', 'food_item')},
        ),
    ]
