# Generated by Django 5.2.1 on 2025-05-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0012_alter_daydiet_unique_together'),
    ]

    operations = [
    ]
