# Generated by Django 5.1.7 on 2025-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_cadera_person_cintura_person_cuello_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='imc',
            field=models.FloatField(default=0),
        ),
    ]
