# Generated by Django 5.1.7 on 2025-04-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_cadera_person_cintura_person_cuello_and_more'),
        ('workout_routines', '0003_remove_exercise_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='workouts',
            field=models.ManyToManyField(to='workout_routines.workout'),
        ),
    ]
