# Generated by Django 5.1.7 on 2025-04-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_workouts'),
        ('workout_routines', '0003_remove_exercise_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='workouts',
            field=models.ManyToManyField(blank=True, to='workout_routines.workout'),
        ),
    ]
