# Generated by Django 5.1.7 on 2025-04-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diets', '0001_initial'),
        ('persons', '0004_alter_person_workouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='diets',
            field=models.ManyToManyField(blank=True, to='diets.semanaldiet'),
        ),
    ]
