# Generated by Django 5.2 on 2025-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_remove_person_workouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='diary_callories',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Calorías diarias'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imc',
            field=models.FloatField(default=0, verbose_name='Índice de masa corporal'),
        ),
    ]
