# Generated by Django 5.2 on 2025-04-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_person_diary_callories_alter_person_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=170, help_text='Altura en centímetros', verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='imc',
            field=models.FloatField(default=0),
        ),
    ]
