# Generated by Django 5.2 on 2025-04-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_alter_person_height_alter_person_imc'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='edad',
            field=models.PositiveIntegerField(default=18, verbose_name='Edad'),
        ),
    ]
