# Generated by Django 5.2 on 2025-04-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_person_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fitness_goal',
            field=models.CharField(choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('maintain', 'Mantenimiento'), ('improve_endurance', 'Mejorar resistencia')], default='maintain', max_length=20, null=True, verbose_name='Objetivo principal'),
        ),
    ]
