# Generated by Django 5.1.7 on 2025-05-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_alter_person_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='workout_level',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('amateur', 'Amateur'), ('profesional', 'Profesional'), ('culturista', 'Culturista')], default='amateur', max_length=100),
        ),
    ]
