# Generated by Django 5.1.7 on 2025-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_person_workout_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='workout_level',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('amateur', 'Amateur'), ('profesional', 'Profesional'), ('culturista', 'Culturista')], default='amateur', max_length=100, verbose_name='Nivel de entrenamiento'),
        ),
    ]
