# Generated by Django 5.1.7 on 2025-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_alter_person_workout_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default.png', upload_to='profile_pics/', verbose_name='Foto de perfil'),
        ),
    ]
