# Generated by Django 5.2.1 on 2025-05-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fitness_goal',
            field=models.CharField(choices=[('lose_weight', 'Perder peso'), ('gain_muscle', 'Ganar músculo'), ('maintain', 'Mantenimiento')], default='maintain', max_length=20, null=True, verbose_name='Objetivo principal'),
        ),
    ]
