# Generated by Django 5.1.7 on 2025-04-03 17:21

from django.db import migrations



def poblar_ejercicios(apps, schema_editor):
    Equipment = apps.get_model('workout_routines', 'Equipment')
    MuscleGroup = apps.get_model('workout_routines', 'MuscleGroup')
    Exercise = apps.get_model('workout_routines', 'Exercise')

    manc = Equipment.objects.create(name='Mancuernas')
    barra = Equipment.objects.create(name='Barra libre')
    pecho = MuscleGroup.objects.create(name='Pecho')
    hombro = MuscleGroup.objects.create(name='Hombro')
    triceps = MuscleGroup.objects.create(name='Triceps')
    espalda = MuscleGroup.objects.create(name='Espalda')
    biceps = MuscleGroup.objects.create(name='Biceps')
    abdomen = MuscleGroup.objects.create(name='Abdomen')
    cuadriceps = MuscleGroup.objects.create(name='Cuádriceps')
    femoral = MuscleGroup.objects.create(name='Femoral')
    gemelo = MuscleGroup.objects.create(name='Gemelo')

    press_banca = Exercise.objects.create(name='Press banca', description='El Press banca es un gran ejercicio multialticular que sirve para el desarrollo sobre todo del pectoral, aunque trabaja indirectamente los hombros y los triceps.')
    press_banca.muscle_groups.add(pecho, hombro, triceps)
    press_banca.equipment_needed.add(manc, barra)
    press_banca.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routines', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_ejercicios),
    ]
