# Generated by Django 5.1.7 on 2025-03-30 12:11

from django.db import migrations

def poblar_ejercicios(apps, schema_editor):
    Exercise = apps.get_model('workout_routines', 'Exercise')
    MuscleGroup = apps.get_model('workout_routines', 'MuscleGroup')

    pecho = MuscleGroup.objects.create(name='Pectoral')
    triceps = MuscleGroup.objects.create(name='Triceps')
    hombro = MuscleGroup.objects.create(name='Hombro')

    press_banca = Exercise.objects.create(name="Press Banca",
                                          description="Buen ejercicio para aumentar masa muscular en el pectoral")

    press_banca.muscle_groups.set([pecho,triceps,hombro])


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routines', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(poblar_ejercicios),
    ]
