# Generated by Django 5.2 on 2025-04-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routines', '0005_alter_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='precargado',
            field=models.BooleanField(default=False),
        ),
    ]
