# Generated by Django 5.1.7 on 2025-05-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routines', '0007_alter_workout_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='nivel',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('amateur', 'Amateur'), ('avanzado', 'Avanzado'), ('elite', 'Elite'), ('culturista', 'Culturista')], max_length=100, null=True),
        ),
    ]
