# Generated by Django 5.1.7 on 2025-05-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_routines', '0008_workout_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='nivel',
            field=models.CharField(blank=True, choices=[('principiante', 'Principiante'), ('amateur', 'Amateur'), ('profesional', 'Profesional'), ('culturista', 'Culturista')], max_length=100, null=True),
        ),
    ]
