# Generated by Django 5.1.7 on 2025-04-03 17:21

from django.db import migrations


def poblar_ejercicios(apps, schema_editor):
    Equipment = apps.get_model('workout_routines', 'Equipment')
    MuscleGroup = apps.get_model('workout_routines', 'MuscleGroup')
    Exercise = apps.get_model('workout_routines', 'Exercise')
    Workout = apps.get_model('workout_routines', 'Workout')
    RoutineExercise = apps.get_model('workout_routines', 'RoutineExercise')

    equip_names = [
        'Mancuernas', 'Barra libre', 'Polea alta', 'Polea baja',
        'Multiestación', 'Máquina Smith', 'Máquina de remo'
    ]
    musc_names = [
        'Pecho', 'Hombro', 'Triceps', 'Espalda', 'Biceps',
        'Abdomen', 'Cuádriceps', 'Femoral', 'Gemelo', 'Trapecio'
    ]

    equips = {name: Equipment.objects.get_or_create(name=name)[0] for name in equip_names}
    muscs = {name: MuscleGroup.objects.get_or_create(name=name)[0] for name in musc_names}

    ejercicios = [
        {
            'name': 'Press banca plano',
            'desc': 'Ejercicio multiarticular para pectoral, hombros y tríceps.',
            'mgs': ['Pecho', 'Hombro', 'Triceps'],
            'eqs': ['Barra libre', 'Máquina Smith']
        },
        {
            'name': 'Press inclinado con mancuernas',
            'desc': 'Focaliza la parte superior del pectoral y deltoides anterior.',
            'mgs': ['Pecho', 'Hombro'],
            'eqs': ['Mancuernas']
        },
        {
            'name': 'Aperturas en máquina',
            'desc': 'Aísla el pectoral mayor con poca implicación de tríceps.',
            'mgs': ['Pecho'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Jalón al pecho',
            'desc': 'Trabaja dorsal ancho y bíceps de forma primaria.',
            'mgs': ['Espalda', 'Biceps'],
            'eqs': ['Polea alta']
        },
        {
            'name': 'Remo con barra',
            'desc': 'Fortalece toda la zona media y superior de la espalda.',
            'mgs': ['Espalda', 'Trapecio', 'Biceps'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Remo en máquina',
            'desc': 'Versión guiada del remo, menos estabilización.',
            'mgs': ['Espalda', 'Trapecio', 'Biceps'],
            'eqs': ['Máquina de remo']
        },
        {
            'name': 'Curl bíceps con barra',
            'desc': 'Aísla el bíceps braquial con barra recta.',
            'mgs': ['Biceps'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Curl martillo con mancuernas',
            'desc': 'Trabaja braquial y antebrazo.',
            'mgs': ['Biceps'],
            'eqs': ['Mancuernas']
        },
        {
            'name': 'Sentadilla trasera',
            'desc': 'Rey de los ejercicios de pierna: cuádriceps, glúteos y femoral.',
            'mgs': ['Cuádriceps', 'Femoral'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Prensa de piernas',
            'desc': 'Ejercicio guiado para cuádriceps y glúteos.',
            'mgs': ['Cuádriceps'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Extensión de piernas',
            'desc': 'Aíslan el cuádriceps.',
            'mgs': ['Cuádriceps'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Curl femoral tumbado',
            'desc': 'Aísla el femoral en máquina.',
            'mgs': ['Femoral'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Elevación de talones de pie',
            'desc': 'Fortalece los gemelos.',
            'mgs': ['Gemelo'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Press militar',
            'desc': 'Trabaja hombros y tríceps en barra.',
            'mgs': ['Hombro', 'Triceps'],
            'eqs': ['Barra libre', 'Máquina Smith']
        },
        {
            'name': 'Elevaciones laterales con mancuernas',
            'desc': 'Aíslan deltoides medio.',
            'mgs': ['Hombro'],
            'eqs': ['Mancuernas']
        },
        {
            'name': 'Fondos en paralelas',
            'desc': 'Trabaja pecho inferior y tríceps.',
            'mgs': ['Pecho', 'Triceps'],
            'eqs': []
        },
        {
            'name': 'Crunch abdominal',
            'desc': 'Ejercicio básico para abdomen.',
            'mgs': ['Abdomen'],
            'eqs': []
        },
        {
            'name': 'Press declinado con barra',
            'desc': 'Enfocado en la parte inferior del pectoral.',
            'mgs': ['Pecho', 'Triceps'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Flexiones con peso',
            'desc': 'Ejercicio básico para desarrollo pectoral con carga adicional.',
            'mgs': ['Pecho', 'Triceps'],
            'eqs': []
        },
        {
            'name': 'Pullover con mancuerna',
            'desc': 'Ejercicio para expansión torácica y trabajo de serrato.',
            'mgs': ['Pecho', 'Espalda'],
            'eqs': ['Mancuernas']
        },

        # Espalda
        {
            'name': 'Peso muerto convencional',
            'desc': 'Ejercicio completo para espalda baja y cadena posterior.',
            'mgs': ['Espalda', 'Femoral', 'Trapecio'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Dominadas pronadas',
            'desc': 'Ejercicio fundamental para desarrollo de espalda ancha.',
            'mgs': ['Espalda', 'Biceps'],
            'eqs': []
        },
        {
            'name': 'Remo en T',
            'desc': 'Ejercicio para grosor de espalda media.',
            'mgs': ['Espalda', 'Trapecio', 'Biceps'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Encogimientos con barra',
            'desc': 'Aislamiento de trapecios superiores.',
            'mgs': ['Trapecio'],
            'eqs': ['Barra libre']
        },

        # Hombros
        {
            'name': 'Elevaciones frontales con disco',
            'desc': 'Aislamiento del deltoides anterior.',
            'mgs': ['Hombro'],
            'eqs': []
        },
        {
            'name': 'Pájaros invertidos en máquina',
            'desc': 'Trabajo específico para deltoides posterior.',
            'mgs': ['Hombro', 'Espalda'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Press Arnold',
            'desc': 'Variación de press de hombros con rotación.',
            'mgs': ['Hombro', 'Triceps'],
            'eqs': ['Mancuernas']
        },

        # Piernas
        {
            'name': 'Sentadilla frontal',
            'desc': 'Variante que enfatiza cuádriceps y núcleo.',
            'mgs': ['Cuádriceps', 'Abdomen'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Prensa inclinada',
            'desc': 'Ejercicio guiado para desarrollo completo de pierna.',
            'mgs': ['Cuádriceps', 'Femoral'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Hip thrust con barra',
            'desc': 'Ejercicio fundamental para glúteos y cadena posterior.',
            'mgs': ['Femoral', 'Espalda'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Peso muerto rumano',
            'desc': 'Enfocado en femoral e isquiotibiales.',
            'mgs': ['Femoral', 'Espalda'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Zancadas con mancuernas',
            'desc': 'Ejercicio unilateral para pierna y glúteos.',
            'mgs': ['Cuádriceps', 'Femoral'],
            'eqs': ['Mancuernas']
        },
        {
            'name': 'Elevación de talones sentado',
            'desc': 'Aislamiento de sóleo (gemelo interno).',
            'mgs': ['Gemelo'],
            'eqs': ['Multiestación']
        },

        # Brazos
        {
            'name': 'Fondos en máquina',
            'desc': 'Variante asistida para tríceps y pecho.',
            'mgs': ['Triceps', 'Pecho'],
            'eqs': ['Multiestación']
        },
        {
            'name': 'Curl predicador',
            'desc': 'Aislamiento de bíceps con apoyo.',
            'mgs': ['Biceps'],
            'eqs': ['Barra libre', 'Máquina Smith']
        },
        {
            'name': 'Extensión de tríceps sobre cabeza',
            'desc': 'Ejercicio completo para tríceps largo.',
            'mgs': ['Triceps'],
            'eqs': ['Mancuernas']
        },
        {
            'name': 'Curl de martillo en polea',
            'desc': 'Variante para braquial y antebrazo.',
            'mgs': ['Biceps'],
            'eqs': ['Polea baja']
        },

        # Abdomen y core
        {
            'name': 'Plancha abdominal',
            'desc': 'Ejercicio isométrico para core completo.',
            'mgs': ['Abdomen'],
            'eqs': []
        },
        {
            'name': 'Russian twists',
            'desc': 'Rotaciones para oblicuos y core.',
            'mgs': ['Abdomen'],
            'eqs': []
        },
        {
            'name': 'Elevaciones de piernas colgado',
            'desc': 'Ejercicio avanzado para abdomen inferior.',
            'mgs': ['Abdomen'],
            'eqs': []
        },

        # Ejercicios compuestos avanzados
        {
            'name': 'Clean and press',
            'desc': 'Ejercicio olímpico completo para fuerza y potencia.',
            'mgs': ['Hombro', 'Espalda', 'Piernas'],
            'eqs': ['Barra libre']
        },
        {
            'name': 'Sentadilla sobre cabeza',
            'desc': 'Ejercicio avanzado de movilidad y fuerza.',
            'mgs': ['Hombro', 'Cuádriceps', 'Abdomen'],
            'eqs': ['Barra libre']
        }
    ]

    ex_objs = {}
    for ex in ejercicios:
        e, created = Exercise.objects.get_or_create(
            name=ex['name'], defaults={'description': ex['desc']}
        )
        for mg in ex['mgs']:
            if mg in muscs:
                e.muscle_groups.add(muscs[mg])
        for eq in ex['eqs']:
            if eq in equips:
                e.equipment_needed.add(equips[eq])
        e.save()
        ex_objs[ex['name']] = e

    workout_ejemplos = {
        # PRINCIPIANTE (2 ejercicios por día + abdomen)
        ('principiante', 'lunes'): [
            'Sentadilla trasera',
            'Prensa de piernas',
            'Crunch abdominal'
        ],
        ('principiante', 'martes'): [
            'Press banca plano',
            'Fondos en máquina',
            'Plancha abdominal'
        ],
        ('principiante', 'miércoles'): [
            'Jalón al pecho',
            'Curl bíceps con barra',
            'Russian twists'
        ],
        ('principiante', 'jueves'): [
            'Peso muerto rumano',
            'Elevación de talones de pie',
            'Elevaciones de piernas colgado'
        ],
        ('principiante', 'viernes'): [
            'Press inclinado con mancuernas',
            'Remo con barra',
            'Crunch abdominal'
        ],

        # AMATEUR (3 ejercicios por día + abdomen)
        ('amateur', 'lunes'): [
            'Sentadilla frontal',
            'Curl femoral tumbado',
            'Prensa inclinada',
            'Plancha abdominal'
        ],
        ('amateur', 'martes'): [
            'Press declinado con barra',
            'Aperturas en máquina',
            'Extensión de tríceps sobre cabeza',
            'Russian twists'
        ],
        ('amateur', 'miércoles'): [
            'Dominadas pronadas',
            'Remo en T',
            'Curl predicador',
            'Elevaciones de piernas colgado'
        ],
        ('amateur', 'jueves'): [
            'Zancadas con mancuernas',
            'Hip thrust con barra',
            'Elevación de talones sentado',
            'Crunch abdominal'
        ],
        ('amateur', 'viernes'): [
            'Pullover con mancuerna',
            'Peso muerto convencional',
            'Flexiones con peso',
            'Plancha abdominal'
        ],

        # PROFESIONAL (4 ejercicios por día + abdomen)
        ('profesional', 'lunes'): [
            'Sentadilla trasera',
            'Peso muerto rumano',
            'Extensión de piernas',
            'Hip thrust con barra',
            'Russian twists'
        ],
        ('profesional', 'martes'): [
            'Press inclinado con mancuernas',
            'Fondos en paralelas',
            'Press Arnold',
            'Extensión de tríceps sobre cabeza',
            'Elevaciones de piernas colgado'
        ],
        ('profesional', 'miércoles'): [
            'Remo con barra',
            'Encogimientos con barra',
            'Curl martillo en polea',
            'Remo en máquina',
            'Crunch abdominal'
        ],
        ('profesional', 'jueves'): [
            'Sentadilla frontal',
            'Prensa de piernas',
            'Curl femoral tumbado',
            'Elevación de talones de pie',
            'Plancha abdominal'
        ],
        ('profesional', 'viernes'): [
            'Press banca plano',
            'Jalón al pecho',
            'Pájaros invertidos en máquina',
            'Pullover con mancuerna',
            'Russian twists'
        ],

        # CULTURISTA (5 ejercicios por día + abdomen)
        ('culturista', 'lunes'): [
            'Sentadilla frontal',
            'Peso muerto convencional',
            'Zancadas con mancuernas',
            'Elevación de talones sentado',
            'Hip thrust con barra',
            'Elevaciones de piernas colgado'
        ],
        ('culturista', 'martes'): [
            'Press declinado con barra',
            'Aperturas en máquina',
            'Press militar',
            'Fondos en máquina',
            'Extensión de tríceps sobre cabeza',
            'Crunch abdominal'
        ],
        ('culturista', 'miércoles'): [
            'Remo en T',
            'Dominadas pronadas',
            'Peso muerto rumano',
            'Curl bíceps con barra',
            'Curl predicador',
            'Plancha abdominal'
        ],
        ('culturista', 'jueves'): [
            'Sentadilla trasera',
            'Prensa inclinada',
            'Curl femoral tumbado',
            'Elevación de talones de pie',
            'Clean and press',
            'Russian twists'
        ],
        ('culturista', 'viernes'): [
            'Press Arnold',
            'Pullover con mancuerna',
            'Remo con barra',
            'Flexiones con peso',
            'Jalón al pecho',
            'Elevaciones de piernas colgado'
        ]
    }

    niveles = ['principiante', 'amateur', 'profesional', 'culturista']
    dias = ['lunes', 'martes', 'miércoles', 'jueves', 'viernes']

    for nivel in niveles:
        for day in dias:
            # Ahora incluimos 'nivel' en el lookup:
            workout_obj, created = Workout.objects.get_or_create(
                name=day,
                nivel=nivel,
                defaults={
                    'precargado': True
                }
            )

            # Obtener los nombres de ejercicios asignados a (nivel, día)
            lista_nombres = workout_ejemplos.get((nivel, day), [])

            # Asociar cada Exercise con este Workout (vía RoutineExercise)
            for nombre_ex in lista_nombres:
                ex_obj = ex_objs.get(nombre_ex)
                if ex_obj:
                    RoutineExercise.objects.get_or_create(
                        workout=workout_obj,
                        exercise=ex_obj,
                        defaults={
                            'sets': 3,
                            'reps': 10,
                            'rest_time': 60
                        }
                    )


class Migration(migrations.Migration):
    dependencies = [
        ('workout_routines', '0009_alter_workout_nivel'),
    ]

    operations = [
        migrations.RunPython(poblar_ejercicios),
    ]
